### PR TITLE
Update versioning

### PR DESCRIPTION
**Pull request by joselsegura**
# Description

Current versioning is always set to 1.0.0, while setuptools_scm is listed as dependency.
This change will provide a similar versioning as the one used in our other Python repositories

## Type of change

- Refactor (refactoring code, removing useless files)

## Testing steps

Locally run `python setup.py sdist` to check the generated version`

## Checklist
* [ ] `make before_commit` passes
* [ ] updated documentation wherever necessary
* [ ] added or modified tests if necessary
* [ ] updated schemas and validators in [insights-data-schemas](https://github.com/RedHatInsights/insights-data-schemas) in case of input/output change

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
seems legit

**Review by epapbak — APPROVED** [review]
lgtm

**Comment by epapbak** [comment]
> lgtm

Just FYI, there's some warnings when running `setup.py --version` about the usage of dashes (`-`) instead of underscores (`_`) in the setup.cfg file.

**Comment by joselsegura** [comment]
> > lgtm
> 
> Just FYI, there's some warnings when running `setup.py --version` about the usage of dashes (`-`) instead of underscores (`_`) in the setup.cfg file.

Already fixed in the last version. TY!

**Pull request merged**
